# Generated by Django 3.0.3 on 2020-06-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=80)),
            ],
        ),
    ]
